blogviews_index:
    path:     /
    defaults: { _controller: "BlogBundle:BlogViews:index" }
    methods:  GET

blogviews_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:BlogViews:show" }
    methods:  GET

blogviews_new:
    path:     /new
    defaults: { _controller: "BlogBundle:BlogViews:new" }
    methods:  [GET, POST]

blogviews_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:BlogViews:edit" }
    methods:  [GET, POST]

blogviews_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:BlogViews:delete" }
    methods:  DELETE
