newsletterlist_index:
    path:     /
    defaults: { _controller: "BlogBundle:NewsLetterList:index" }
    methods:  GET

newsletterlist_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:NewsLetterList:show" }
    methods:  GET

newsletterlist_new:
    path:     /new
    defaults: { _controller: "BlogBundle:NewsLetterList:new" }
    methods:  [GET, POST]

newsletterlist_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:NewsLetterList:edit" }
    methods:  [GET, POST]

newsletterlist_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:NewsLetterList:delete" }
    methods:  DELETE
