newslettertemplate_index:
    path:     /
    defaults: { _controller: "BlogBundle:NewsLetterTemplate:index" }
    methods:  GET

newslettertemplate_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:NewsLetterTemplate:show" }
    methods:  GET

newslettertemplate_new:
    path:     /new
    defaults: { _controller: "BlogBundle:NewsLetterTemplate:new" }
    methods:  [GET, POST]

newslettertemplate_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:NewsLetterTemplate:edit" }
    methods:  [GET, POST]

newslettertemplate_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:NewsLetterTemplate:delete" }
    methods:  DELETE
