<?php

namespace ForumBundle\Repository;


/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{
    public function findidtopic($sujet,$contenu,$imageName,$idt,$idu)
    {
        $q = $this->getEntityManager()
            ->createQuery("UPDATE ForumBundle:Topic t SET t.sujet=:sujet,t.Contenu=:contenu,t.image_name=:imageName WHERE t.id=idt AND t.id_user=:idu")
            ->setParameter("sujet", $sujet)
            ->setParameter("contenu",$contenu)
            ->setParameter("imageName",$imageName)
            ->setParameter("idt",$idt)
            ->setParameter("idu",$idu);
        return $q->getResult();

    }


    public function findTopicAjax($suj){

        $query =$this->getEntityManager()
            ->createQuery("SELECT t FROM ForumBundle:Topic t JOIN t.user u WHERE t.sujet LIKE :suj OR u.username LIKE :us")
            ->setParameter("suj",'%'.$suj.'%')
            ->setParameter("us",'%'.$suj.'%');

        return $query->getResult();
    }

    public function findMobile($suj){

        $query =$this->getEntityManager()
            ->createQuery("SELECT t FROM ForumBundle:Topic t WHERE t.sujet LIKE :suj")
            ->setParameter("suj",'%'.$suj.'%');

        return $query->getResult();
    }

    public function userMobile($x){

        $query =$this->getEntityManager()
            ->createQuery("SELECT u.username FROM ForumBundle:Topic t  JOIN t.user u WHERE t.id = :x ")
            ->setParameter('x',$x);

        return $query->getResult();
    }

}
