<?php

namespace ForumBundle\Repository;

/**
 * UserForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserForumRepository extends \Doctrine\ORM\EntityRepository
{
}
