<?php

namespace BlogBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBlogForViews(){
        $q = $this->getEntityManager()->createQuery('SELECT CAST(dateVisite AS date) FROM BlogBundle:BlogViews WHERE blog_id = 1');

    }
}
