<?php

namespace BlogBundle\Repository;

/**
 * NotificationBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationBlogRepository extends \Doctrine\ORM\EntityRepository
{
}
