profil_index:
    path:     /
    defaults: { _controller: "GestionCvBundle:Profil:index" }
    methods:  GET

profil_show:
    path:     /{id}/show
    defaults: { _controller: "GestionCvBundle:Profil:show" }
    methods:  GET

profil_new:
    path:     /new
    defaults: { _controller: "GestionCvBundle:Profil:new" }
    methods:  [GET, POST]

profil_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionCvBundle:Profil:edit" }
    methods:  [GET, POST]

profil_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionCvBundle:Profil:delete" }
    methods:  DELETE
profil_test:
    path:     /{id}/test
    defaults: { _controller: "GestionCvBundle:Profil:test" }
    methods:  GET

