<?php

namespace FixitBundle\Repository;

/**
 * addressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class addressRepository extends \Doctrine\ORM\EntityRepository
{
}
