<?php

namespace FixitBundle\Repository;

/**
 * BlogViewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogViewsRepository extends \Doctrine\ORM\EntityRepository
{
}
