<?php

namespace FixitBundle\Repository;

/**
 * BlogCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
