<?php

namespace FixitBundle\Repository;

/**
 * categorieifixitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieifixitRepository extends \Doctrine\ORM\EntityRepository
{
}
