<?php

namespace FixitBundle\Repository;

/**
 * categorieEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieEventRepository extends \Doctrine\ORM\EntityRepository
{
}
