<?php

namespace FixitBundle\Repository;

/**
 * deliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class deliveryRepository extends \Doctrine\ORM\EntityRepository
{
}
