<?php

namespace FixitBundle\Repository;

/**
 * factrueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class factrueRepository extends \Doctrine\ORM\EntityRepository
{
}
