<?php

namespace FixitBundle\Repository;

/**
 * IfixitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IfixitRepository extends \Doctrine\ORM\EntityRepository
{
}
