<?php

namespace FixitBundle\Repository;

/**
 * NewsLetterListUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterListUserRepository extends \Doctrine\ORM\EntityRepository
{
}
