<?php

namespace FixitBundle\Repository;

/**
 * NewsLetterTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
