<?php

namespace FixitBundle\Repository;

/**
 * NewsLetterListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterListRepository extends \Doctrine\ORM\EntityRepository
{
}
