<?php

namespace FixitBundle\Repository;

/**
 * ParticpantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticpantRepository extends \Doctrine\ORM\EntityRepository
{
}
