<?php

namespace FixitBundle\Repository;

/**
 * RecomendedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecomendedRepository extends \Doctrine\ORM\EntityRepository
{

}
