<?php

namespace FixitBundle\Repository;

/**
 * serviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceRepository extends \Doctrine\ORM\EntityRepository
{
}
