<?php

namespace FixitBundle\Repository;

/**
 * WorkshopsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopsRepository extends \Doctrine\ORM\EntityRepository
{
}
